services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_catalog.entity_manager'

    Softspring\CatalogBundle\Controller\:
        resource: '../../../Controller/*'
        public: true

    Softspring\CatalogBundle\Form\:
        resource: '../../../Form/*'

    Softspring\CatalogBundle\Manager\:
        resource: '../../../Manager/*'

    Softspring\CatalogBundle\Request\ParamConverter\:
        resource: '../../../Request/ParamConverter/*'
        tags: ['request.param_converter']

    Softspring\CatalogBundle\Twig\Extension\:
        resource: '../../../Twig/Extension/*'
        tags: ['twig.extension']
