security:
    role_hierarchy:
        ROLE_CATALOG_ADMIN_PRODUCTS:
            - ROLE_CATALOG_ADMIN_PRODUCTS_LIST
            - ROLE_CATALOG_ADMIN_PRODUCTS_CREATE
            - ROLE_CATALOG_ADMIN_PRODUCTS_UPDATE
            - ROLE_CATALOG_ADMIN_PRODUCTS_DELETE
            - ROLE_CATALOG_ADMIN_PRODUCTS_DETAILS
        ROLE_CATALOG_ADMIN_MODELS:
            - ROLE_CATALOG_ADMIN_MODELS_LIST
            - ROLE_CATALOG_ADMIN_MODELS_CREATE
            - ROLE_CATALOG_ADMIN_MODELS_UPDATE
            - ROLE_CATALOG_ADMIN_MODELS_DELETE
            - ROLE_CATALOG_ADMIN_MODELS_DETAILS
        ROLE_CATALOG_ADMIN_PACKS:
            - ROLE_CATALOG_ADMIN_PACKS_LIST
            - ROLE_CATALOG_ADMIN_PACKS_CREATE
            - ROLE_CATALOG_ADMIN_PACKS_UPDATE
            - ROLE_CATALOG_ADMIN_PACKS_DELETE
            - ROLE_CATALOG_ADMIN_PACKS_DETAILS
        ROLE_CATALOG_ADMIN_RO:
            - ROLE_CATALOG_ADMIN_MODELS_LIST
            - ROLE_CATALOG_ADMIN_MODELS_DETAILS
            - ROLE_CATALOG_ADMIN_PRODUCTS_LIST
            - ROLE_CATALOG_ADMIN_PRODUCTS_DETAILS
            - ROLE_CATALOG_ADMIN_PACKS_LIST
            - ROLE_CATALOG_ADMIN_PACKS_DETAILS