sfs_catalog_admin_models_list:
    controller: sfs_catalog.admin.model.controller::list
    path: /

sfs_catalog_admin_models_create:
    controller: sfs_catalog.admin.model.controller::create
    path: /create
