services:
    sfs_catalog.admin.model.controller:
        class: Softspring\AdminBundle\Controller\EntityController
        public: true
        arguments:
            $manager: '@Softspring\CatalogBundle\Manager\ModelManagerInterface'
            $eventDispatcher: '@event_dispatcher'
            $listFilterForm: '@Softspring\CatalogBundle\Form\Admin\ModelListFilterFormInterface'
            $createForm: '@Softspring\CatalogBundle\Form\Admin\ModelCreateFormInterface'
            $updateForm: '@Softspring\CatalogBundle\Form\Admin\ModelUpdateFormInterface'
            $deleteForm: '@Softspring\CatalogBundle\Form\Admin\ModelDeleteFormInterface'
            $config:
                list:
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_LIST_VIEW
                    view: '@@SfsCatalog/admin/model/list.html.twig'
                    view_page: '@@SfsCatalog/admin/model/list-page.html.twig'
                create:
                    initialize_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_CREATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_CREATE_FORM_VALID
                    success_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_CREATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_CREATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_CREATE_VIEW
                    success_redirect_to: 'sfs_catalog_admin_models_list'
                    view: '@@SfsCatalog/admin/model/create.html.twig'
                update:
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_UPDATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_UPDATE_FORM_VALID
                    success_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_UPDATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_UPDATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_UPDATE_VIEW
                    success_redirect_to: 'sfs_catalog_admin_models_list'
                    view: '@@SfsCatalog/admin/model/update.html.twig'
                delete:
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_DELETE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_DELETE_FORM_VALID
                    success_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_DELETE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_DELETE_FORM_INVALID
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_DELETE_VIEW
                    success_redirect_to: 'sfs_catalog_admin_models_list'
                    view: '@@SfsCatalog/admin/model/delete.html.twig'
                read:
                    param_converter_key: 'id'
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_READ_VIEW
                    view: '@@SfsCatalog/admin/model/read.html.twig'