parameters:
    sfs_catalog.admin.products.list_view: '@@SfsCatalog/admin/product/list.html.twig'
    sfs_catalog.admin.products.list_page_view: '@@SfsCatalog/admin/product/list-page.html.twig'
    sfs_catalog.admin.products.create_view: '@@SfsCatalog/admin/product/create.html.twig'
    sfs_catalog.admin.products.update_view: '@@SfsCatalog/admin/product/update.html.twig'
    sfs_catalog.admin.products.delete_view: '@@SfsCatalog/admin/product/delete.html.twig'
    sfs_catalog.admin.products.read_view: '@@SfsCatalog/admin/product/read.html.twig'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\CatalogBundle\Form\Admin\:
        resource: '../../../Form/Admin/Product*'

    sfs_catalog.admin.product.controller:
        class: Softspring\CrudlBundle\Controller\CrudlController
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $manager: '@Softspring\CatalogBundle\Manager\ProductManagerInterface'
            $listFilterForm: '@Softspring\CatalogBundle\Form\Admin\ProductListFilterFormInterface'
            $createForm: '@Softspring\CatalogBundle\Form\Admin\ProductCreateFormInterface'
            $updateForm: '@Softspring\CatalogBundle\Form\Admin\ProductUpdateFormInterface'
            $deleteForm: '@Softspring\CatalogBundle\Form\Admin\ProductDeleteFormInterface'
            $config:
                entity_attribute: 'product'
                list:
                    is_granted: 'ROLE_CATALOG_ADMIN_PRODUCTS_LIST'
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_LIST_VIEW
                    view: '%sfs_catalog.admin.products.list_view%'
                    view_page: '%sfs_catalog.admin.products.list_page_view%'
                create:
                    is_granted: 'ROLE_CATALOG_ADMIN_PRODUCTS_CREATE'
                    initialize_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_CREATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_CREATE_FORM_VALID
                    success_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_CREATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_CREATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_CREATE_VIEW
                    success_redirect_to: 'sfs_catalog_admin_products_list'
                    view: '%sfs_catalog.admin.products.create_view%'
                update:
                    is_granted: 'ROLE_CATALOG_ADMIN_PRODUCTS_UPDATE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_UPDATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_UPDATE_FORM_VALID
                    success_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_UPDATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_UPDATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_UPDATE_VIEW
                    success_redirect_to: 'sfs_catalog_admin_products_list'
                    view: '%sfs_catalog.admin.products.update_view%'
                delete:
                    is_granted: 'ROLE_CATALOG_ADMIN_PRODUCTS_DELETE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_DELETE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_DELETE_FORM_VALID
                    success_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_DELETE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_DELETE_FORM_INVALID
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_DELETE_VIEW
                    success_redirect_to: 'sfs_catalog_admin_products_list'
                    view: '%sfs_catalog.admin.products.delete_view%'
                read:
                    is_granted: 'ROLE_CATALOG_ADMIN_PRODUCTS_DETAILS'
                    param_converter_key: 'id'
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_READ_VIEW
                    view: '%sfs_catalog.admin.products.read_view%'