services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\CatalogBundle\Form\Admin\:
        resource: '../../../Form/Admin/Product*'

    sfs_catalog.admin.product.controller:
        class: Softspring\AdminBundle\Controller\EntityController
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $manager: '@Softspring\CatalogBundle\Manager\ProductManagerInterface'
            $eventDispatcher: '@event_dispatcher'
            $listFilterForm: '@Softspring\CatalogBundle\Form\Admin\ProductListFilterFormInterface'
            $createForm: '@Softspring\CatalogBundle\Form\Admin\ProductCreateFormInterface'
            $updateForm: '@Softspring\CatalogBundle\Form\Admin\ProductUpdateFormInterface'
            $deleteForm: '@Softspring\CatalogBundle\Form\Admin\ProductDeleteFormInterface'
            $config:
                list:
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_LIST_VIEW
                    view: '@@SfsCatalog/admin/product/list.html.twig'
                    view_page: '@@SfsCatalog/admin/product/list-page.html.twig'
                create:
                    initialize_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_CREATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_CREATE_FORM_VALID
                    success_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_CREATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_CREATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_CREATE_VIEW
                    success_redirect_to: 'sfs_catalog_admin_products_list'
                    view: '@@SfsCatalog/admin/product/create.html.twig'
                update:
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_UPDATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_UPDATE_FORM_VALID
                    success_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_UPDATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_UPDATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_UPDATE_VIEW
                    success_redirect_to: 'sfs_catalog_admin_products_list'
                    view: '@@SfsCatalog/admin/product/update.html.twig'
                delete:
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_DELETE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_DELETE_FORM_VALID
                    success_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_DELETE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_DELETE_FORM_INVALID
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_DELETE_VIEW
                    success_redirect_to: 'sfs_catalog_admin_products_list'
                    view: '@@SfsCatalog/admin/product/delete.html.twig'
                read:
                    param_converter_key: 'id'
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_PRODUCTS_READ_VIEW
                    view: '@@SfsCatalog/admin/product/read.html.twig'