parameters:
    sfs_catalog.admin.models.list_view: '@@SfsCatalog/admin/model/list.html.twig'
    sfs_catalog.admin.models.list_page_view: '@@SfsCatalog/admin/model/list-page.html.twig'
    sfs_catalog.admin.models.create_view: '@@SfsCatalog/admin/model/create.html.twig'
    sfs_catalog.admin.models.update_view: '@@SfsCatalog/admin/model/update.html.twig'
    sfs_catalog.admin.models.delete_view: '@@SfsCatalog/admin/model/delete.html.twig'
    sfs_catalog.admin.models.read_view: '@@SfsCatalog/admin/model/read.html.twig'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\CatalogBundle\Form\Admin\:
        resource: '../../../Form/Admin/Model*'

    sfs_catalog.admin.model.controller:
        class: Softspring\CrudlBundle\Controller\CrudlController
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $manager: '@Softspring\CatalogBundle\Manager\ModelManagerInterface'
            $listFilterForm: '@Softspring\CatalogBundle\Form\Admin\ModelListFilterFormInterface'
            $createForm: '@Softspring\CatalogBundle\Form\Admin\ModelCreateFormInterface'
            $updateForm: '@Softspring\CatalogBundle\Form\Admin\ModelUpdateFormInterface'
            $deleteForm: '@Softspring\CatalogBundle\Form\Admin\ModelDeleteFormInterface'
            $config:
                entity_attribute: 'model'
                list:
                    is_granted: 'ROLE_CATALOG_ADMIN_MODELS_LIST'
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_LIST_VIEW
                    view: '%sfs_catalog.admin.models.list_view%'
                    view_page: '%sfs_catalog.admin.models.list_page_view%'
                create:
                    is_granted: 'ROLE_CATALOG_ADMIN_MODELS_CREATE'
                    initialize_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_CREATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_CREATE_FORM_VALID
                    success_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_CREATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_CREATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_CREATE_VIEW
                    success_redirect_to: 'sfs_catalog_admin_models_list'
                    view: '%sfs_catalog.admin.models.create_view%'
                update:
                    is_granted: 'ROLE_CATALOG_ADMIN_MODELS_UPDATE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_UPDATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_UPDATE_FORM_VALID
                    success_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_UPDATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_UPDATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_UPDATE_VIEW
                    success_redirect_to: 'sfs_catalog_admin_models_list'
                    view: '%sfs_catalog.admin.models.update_view%'
                delete:
                    is_granted: 'ROLE_CATALOG_ADMIN_MODELS_DELETE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_DELETE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_DELETE_FORM_VALID
                    success_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_DELETE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_DELETE_FORM_INVALID
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_DELETE_VIEW
                    success_redirect_to: 'sfs_catalog_admin_models_list'
                    view: '%sfs_catalog.admin.models.delete_view%'
                read:
                    is_granted: 'ROLE_CATALOG_ADMIN_MODELS_DETAILS'
                    param_converter_key: 'id'
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_MODELS_READ_VIEW
                    view: '%sfs_catalog.admin.models.read_view%'