parameters:
    sfs_catalog.admin.categories.list_view: '@@SfsCatalog/admin/category/list.html.twig'
    sfs_catalog.admin.categories.list_page_view: '@@SfsCatalog/admin/category/list-page.html.twig'
    sfs_catalog.admin.categories.create_view: '@@SfsCatalog/admin/category/create.html.twig'
    sfs_catalog.admin.categories.update_view: '@@SfsCatalog/admin/category/update.html.twig'
    sfs_catalog.admin.categories.delete_view: '@@SfsCatalog/admin/category/delete.html.twig'
    sfs_catalog.admin.categories.read_view: '@@SfsCatalog/admin/category/read.html.twig'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\CatalogBundle\Form\Admin\:
        resource: '../../../Form/Admin/Category*'

    sfs_catalog.admin.category.controller:
        class: Softspring\CrudlBundle\Controller\CrudlController
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $manager: '@Softspring\CatalogBundle\Manager\CategoryManagerInterface'
            $listFilterForm: '@Softspring\CatalogBundle\Form\Admin\CategoryListFilterFormInterface'
            $createForm: '@Softspring\CatalogBundle\Form\Admin\CategoryCreateFormInterface'
            $updateForm: '@Softspring\CatalogBundle\Form\Admin\CategoryUpdateFormInterface'
            $deleteForm: '@Softspring\CatalogBundle\Form\Admin\CategoryDeleteFormInterface'
            $config:
                entity_attribute: 'category'
                list:
                    is_granted: 'ROLE_CATALOG_ADMIN_CATEGORIES_LIST'
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_CATEGORIES_LIST_VIEW
                    view: '%sfs_catalog.admin.categories.list_view%'
                    view_page: '%sfs_catalog.admin.categories.list_page_view%'
                create:
                    is_granted: 'ROLE_CATALOG_ADMIN_CATEGORIES_CREATE'
                    initialize_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_CATEGORIES_CREATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_CATEGORIES_CREATE_FORM_VALID
                    success_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_CATEGORIES_CREATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_CATEGORIES_CREATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_CATEGORIES_CREATE_VIEW
                    success_redirect_to: 'sfs_catalog_admin_categories_list'
                    view: '%sfs_catalog.admin.categories.create_view%'
                update:
                    is_granted: 'ROLE_CATALOG_ADMIN_CATEGORIES_UPDATE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_CATEGORIES_UPDATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_CATEGORIES_UPDATE_FORM_VALID
                    success_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_CATEGORIES_UPDATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_CATEGORIES_UPDATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_CATEGORIES_UPDATE_VIEW
                    success_redirect_to: 'sfs_catalog_admin_categories_list'
                    view: '%sfs_catalog.admin.categories.update_view%'
                delete:
                    is_granted: 'ROLE_CATALOG_ADMIN_CATEGORIES_DELETE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_CATEGORIES_DELETE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_CATEGORIES_DELETE_FORM_VALID
                    success_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_CATEGORIES_DELETE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_CATEGORIES_DELETE_FORM_INVALID
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_CATEGORIES_DELETE_VIEW
                    success_redirect_to: 'sfs_catalog_admin_categories_list'
                    view: '%sfs_catalog.admin.categories.delete_view%'
                read:
                    is_granted: 'ROLE_CATALOG_ADMIN_CATEGORIES_DETAILS'
                    param_converter_key: 'id'
                    view_event_name: !php/const Softspring\CatalogBundle\SfsCatalogEvents::ADMIN_CATEGORIES_READ_VIEW
                    view: '%sfs_catalog.admin.categories.read_view%'