services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_catalog.entity_manager'

    Softspring\CatalogBundle\Manager\ModelManager: ~
    Softspring\CatalogBundle\Manager\ModelManagerInterface:
        alias: 'Softspring\CatalogBundle\Manager\ModelManager'
        

