services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_catalog.entity_manager'

    Softspring\CatalogBundle\Manager\PackManager: ~
    Softspring\CatalogBundle\Manager\PackManagerInterface:
        alias: 'Softspring\CatalogBundle\Manager\PackManager'

    Softspring\CatalogBundle\Manager\PackProductManager: ~
    Softspring\CatalogBundle\Manager\PackProductManagerInterface:
        alias: 'Softspring\CatalogBundle\Manager\PackProductManager'

