services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_catalog.entity_manager'

    Softspring\CatalogBundle\Manager\ProductManager: ~
    Softspring\CatalogBundle\Manager\ProductManagerInterface:
        alias: 'Softspring\CatalogBundle\Manager\ProductManager'


